# Generated by Django 2.2 on 2019-05-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_comment_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='user',
        ),
    ]
