# Generated by Django 2.2 on 2019-05-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190509_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_disable',
            field=models.BooleanField(default=False),
        ),
    ]
