# Generated by Django 2.2 on 2019-07-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20190719_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
