# Generated by Django 2.2 on 2019-07-19 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_auto_20190719_1131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
