# Generated by Django 2.2 on 2019-07-19 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='comment_user',
            new_name='role_user',
        ),
    ]
