# Generated by Django 2.2 on 2019-07-19 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20190719_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date_posted',
            new_name='timestamp',
        ),
    ]
