# Generated by Django 2.2 on 2019-05-07 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stickypic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stickypic/')),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('source', models.URLField(max_length=250)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ManyToManyField(blank=True, related_name='stickypic_liked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-update_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=160, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stickypic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_stickypic', to='stickypics.Stickypic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickypic_comment_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
